/* eslint-disable no-unused-vars */
const __BUILD_MANIFEST = (function (
  c,
  a,
  s,
  e,
  t,
  n,
  i,
  o,
  u,
  r,
  d,
  p,
  f,
  b,
  g,
  k,
  h,
  l,
  j
) {
  return {
    __rewrites: {
      beforeFiles: [],
      afterFiles: [
        {
          source: "/inapp/notification",
          destination: f,
        },
        {
          source: "/notification/overlay",
          destination: f,
        },
        {
          source: "/inapp/search",
          destination: "/search?in_app_rewrite=true",
        },
        {
          source: "/manifest.webmanifest",
          destination: "/api/manifest.webmanifest",
        },
        {
          source: "/sitemap.xml",
          destination: "/api/sitemap.xml",
        },
        {
          source: "/app-ads.txt",
          destination: "/api/app-ads.txt",
        },
        {
          source: "/account/leave",
          destination: b,
        },
        {
          source: "/category/:categoryId",
          destination: "/category/bestsellers/:categoryId",
        },
      ],
      fallback: [],
    },
    "/": ["static/chunks/pages/index-70b5557c39688f36.js"],
    "/_error": ["static/chunks/pages/_error-d73bb15dd770ad64.js"],
    "/account/change-id": [
      a,
      "static/chunks/pages/account/change-id-37fcc35c3099b3b0.js",
    ],
    "/account/change-password": [
      a,
      s,
      e,
      n,
      r,
      "static/chunks/pages/account/change-password-a6894e67c9406fa7.js",
    ],
    "/account/check-expose": [
      "static/chunks/pages/account/check-expose-e4a83d64ea7b9b41.js",
    ],
    "/account/check-password": [
      "static/chunks/pages/account/check-password-c53a9e8e2bce72ec.js",
    ],
    "/account/devices": [
      c,
      s,
      t,
      e,
      u,
      "static/chunks/pages/account/devices-5bf791162a7a6ae3.js",
    ],
    "/account/email/send": [
      c,
      a,
      n,
      u,
      "static/chunks/pages/account/email/send-024df086e8f737f6.js",
    ],
    "/account/email/verify": [
      n,
      "static/chunks/pages/account/email/verify-3e1f5a45c0c3b589.js",
    ],
    "/account/find-id": [
      c,
      a,
      s,
      n,
      d,
      "static/chunks/pages/account/find-id-c7a9ff4daba04987.js",
    ],
    "/account/find-password": [
      c,
      a,
      s,
      n,
      d,
      "static/chunks/pages/account/find-password-7d4f1455de0b49e7.js",
    ],
    "/account/login": [
      c,
      a,
      s,
      n,
      d,
      "static/chunks/pages/account/login-d88632c0dfc2cdaa.js",
    ],
    "/account/parental-consent/callback/failure": [
      c,
      n,
      u,
      "static/chunks/pages/account/parental-consent/callback/failure-7f56e0ea30ba5f9b.js",
    ],
    "/account/parental-consent/callback/success": [
      "static/chunks/pages/account/parental-consent/callback/success-c40a4601176f86a1.js",
    ],
    "/account/reset-password": [
      a,
      s,
      n,
      r,
      "static/chunks/pages/account/reset-password-2517588da57da0ec.js",
    ],
    "/account/secede": [
      c,
      a,
      s,
      t,
      e,
      n,
      g,
      "static/chunks/pages/account/secede-3f4b6dacb1aa4c74.js",
    ],
    "/account/signup": [
      c,
      n,
      u,
      "static/chunks/pages/account/signup-a1e557b4da4e00ad.js",
    ],
    "/account/signup/complete": [
      c,
      n,
      "static/chunks/pages/account/signup/complete-f74ebef3f2c34dc2.js",
    ],
    "/account/signup/form": [
      a,
      s,
      n,
      u,
      r,
      "static/chunks/pages/account/signup/form-ed3576fd0de5e8d1.js",
    ],
    "/account/verify-adult": [
      c,
      a,
      n,
      "static/chunks/pages/account/verify-adult-c062d68e8989175f.js",
    ],
    "/account/verify-adult/callback": [
      "static/chunks/pages/account/verify-adult/callback-e144582f533b12b9.js",
    ],
    "/bestsellers/[genre]": [
      c,
      k,
      a,
      s,
      t,
      e,
      i,
      o,
      p,
      h,
      "static/chunks/pages/bestsellers/[genre]-3292a9e4c057a83b.js",
    ],
    "/category/list": [
      c,
      s,
      t,
      e,
      "static/chunks/pages/category/list-873f1055a1a9083a.js",
    ],
    "/category/[tab]/[category]": [
      c,
      "static/chunks/2905-85838fc028ad12d4.js",
      a,
      s,
      t,
      e,
      i,
      o,
      p,
      "static/chunks/pages/category/[tab]/[category]-7e4aa8eeae640571.js",
    ],
    "/group-tab/[...groupAndUnitIds]": [
      c,
      a,
      s,
      t,
      e,
      i,
      o,
      "static/chunks/8650-eea33196e928f561.js",
      "static/chunks/pages/group-tab/[...groupAndUnitIds]-e4846a3cc9c34097.js",
    ],
    "/inapp/checkout": [
      c,
      "static/chunks/5703-f28fad015c2a715c.js",
      a,
      s,
      "static/chunks/pages/inapp/checkout-3c3974c9b1e03400.js",
    ],
    "/keyword-finder": [
      "static/chunks/pages/keyword-finder-1cc70386631f34e7.js",
    ],
    "/keyword-finder/[genre]": [
      c,
      k,
      "static/chunks/4317-3c648febc72a6a77.js",
      a,
      s,
      t,
      e,
      l,
      i,
      o,
      p,
      h,
      j,
      "static/chunks/pages/keyword-finder/[genre]-1f5ee20482e8fd69.js",
    ],
    "/new-releases/[genre]": [
      c,
      a,
      s,
      t,
      e,
      i,
      o,
      "static/chunks/pages/new-releases/[genre]-86de1a7efa915090.js",
    ],
    "/notification": [
      c,
      a,
      s,
      t,
      e,
      "static/chunks/pages/notification-df7f56e526199bcc.js",
    ],
    "/order/history_point": [
      c,
      a,
      s,
      t,
      g,
      "static/chunks/pages/order/history_point-8497ed5e204ae52e.js",
    ],
    "/partials": [
      c,
      s,
      t,
      e,
      "static/chunks/pages/partials-d0b63739b163cbb6.js",
    ],
    "/search": [
      c,
      a,
      s,
      t,
      e,
      l,
      i,
      o,
      j,
      "static/chunks/pages/search-5ff85496bf180f5d.js",
    ],
    "/selection/[sectionId]": [
      c,
      a,
      s,
      t,
      e,
      i,
      o,
      "static/chunks/pages/selection/[sectionId]-cf29f943ff73b3b7.js",
    ],
    "/[mainHome]": ["static/chunks/pages/[mainHome]-60d8bb8f82bd8445.js"],
    "/[mainHome]/[subHome]": [
      c,
      a,
      s,
      t,
      e,
      i,
      "static/chunks/pages/[mainHome]/[subHome]-8f009b7956b54593.js",
    ],
    sortedPages: [
      "/",
      "/_app",
      "/_error",
      "/account/change-id",
      "/account/change-password",
      "/account/check-expose",
      "/account/check-password",
      "/account/devices",
      "/account/email/send",
      "/account/email/verify",
      "/account/find-id",
      "/account/find-password",
      "/account/login",
      "/account/parental-consent/callback/failure",
      "/account/parental-consent/callback/success",
      "/account/reset-password",
      b,
      "/account/signup",
      "/account/signup/complete",
      "/account/signup/form",
      "/account/verify-adult",
      "/account/verify-adult/callback",
      "/bestsellers/[genre]",
      "/category/list",
      "/category/[tab]/[category]",
      "/group-tab/[...groupAndUnitIds]",
      "/inapp/checkout",
      "/keyword-finder",
      "/keyword-finder/[genre]",
      "/new-releases/[genre]",
      "/notification",
      "/order/history_point",
      "/partials",
      "/search",
      "/selection/[sectionId]",
      "/[mainHome]",
      "/[mainHome]/[subHome]",
    ],
  };
})(
  "static/chunks/9218-8190c7425ba7efee.js",
  "static/chunks/8094-5de3d930ecc50929.js",
  "static/chunks/3890-ca5e7510930daec2.js",
  "static/chunks/1987-6330415e61b5ee1f.js",
  "static/chunks/5857-9dbb46b25f6694f7.js",
  "static/chunks/805-3d586dc2fcbdfd4f.js",
  "static/chunks/1421-d2e4f8767e99ea68.js",
  "static/chunks/3241-074fa0a889fe639b.js",
  "static/chunks/7855-75a5a1dc3c32bf5f.js",
  "static/chunks/8087-17bcd42d8b2b347a.js",
  "static/chunks/6758-38ff8081b795bf7d.js",
  "static/chunks/6151-502545288c996f9b.js",
  "/notification?in_app_rewrite=true",
  "/account/secede",
  "static/chunks/7166-49d783dd67ffc9d4.js",
  "static/chunks/108-419073ddd6175b05.js",
  "static/chunks/9627-df7c67558b92cd6f.js",
  "static/chunks/5923-bca9e23c3ba0e010.js",
  "static/chunks/9808-f9d548449b6db782.js"
);
//self.__BUILD_MANIFEST_CB && self.__BUILD_MANIFEST_CB();
